version: '3'


services:

  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /main.py
    environment:
      - SERVER_PORT=cualquier_cosa_1
    networks:
      - testing_net
    volumes:
      - config_vol:/data1

  client1:
    container_name: client1
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_SERVER_ADDRESS=cualquier_cosa_2
    networks:
      - testing_net
    volumes:
      - config_vol:/data1
    depends_on:
      - server

  client2:
    container_name: client2
    image: client:latest
    entrypoint: /client
    networks:
      - testing_net
    volumes:
      - config_vol:/data1
    depends_on:
      - client1

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24

volumes:
  config_vol:
    external: true